### ISSUE TITLE
[Android 11] - Crashes on Motorola g9-play with a canvas too large exception

### ISSUE THREAD

**Issue by ospfranco** [WebsiteBeaver/react-native-document-scanner-plugin#57]
Hi, I integrated the library into my project and it works on some devices, but on other it crashes.

Here is the stack trace of a moto g9 on which after calling `.scanDocument` it never returns and crashes the entire app:

```text
02-02 10:55:27.901  2783  3454 D Avrcp_ext: AudioManager isPlaying: false
02-02 10:55:27.903  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 15204864, cslDeviceIndex 12 oishandle, hDevice 7274769 name:CSLHwOPE
02-02 10:55:27.903 32546  4306 E McfMlStateMachine: mcf not supported by current mode
02-02 10:55:27.908  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature RealTime Session RealTime
02-02 10:55:27.908  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb4000073438ec040)
02-02 10:55:27.908  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature RealTime Session RealTime
02-02 10:55:27.908  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature RawHDR Session RawHDR
02-02 10:55:27.908  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb4000073228fa040)
02-02 10:55:27.908  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature RawHDR Session RawHDR
02-02 10:55:27.908  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature Bayer2Yuv Session Bayer2Yuv
02-02 10:55:27.908  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb400007320350040)
02-02 10:55:27.908  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature Bayer2Yuv Session Bayer2Yuv
02-02 10:55:27.909  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature JPEG Session JPEG
02-02 10:55:27.909  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb40000731c8ef040)
02-02 10:55:27.909  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature JPEG Session JPEG
02-02 10:55:27.910  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature Memcpy Session Memcpy
02-02 10:55:27.910  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb40000731a414040)
02-02 10:55:27.910  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature Memcpy Session Memcpy
02-02 10:55:27.911  2120  4588 V WindowManager: Changing focus from Window{62a82c0 u0 com.motorola.camera2/com.motorola.camera.Camera} to null displayId=0
02-02 10:55:27.911  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature SWMF Session SWMF
02-02 10:55:27.911  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb400007316eaa040)
02-02 10:55:27.911  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature SWMF Session SWMF
02-02 10:55:27.912  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:491 ExecuteFlushHelper() pSessionData isFlushInProgress TRUE Feature JPEGGPU Session JPEG
02-02 10:55:27.912  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb4000073120ed040)
02-02 10:55:27.912  1215  1805 I CHIUSECASE: [CONFIG ] chifeature2base.cpp:503 ExecuteFlushHelper() pSessionData isFlushInProgress FALSE Feature JPEGGPU Session JPEG
02-02 10:55:27.913  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb4000073438ec040)
02-02 10:55:27.914  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:7417 SetAELockRange() Set AE lock Range from 0 - 0 for PipelineIndex:0
02-02 10:55:27.914  1215  1805 I CamX    : [CONFIG][SENSOR ] camxactuator.cpp:680 OnStreamOff() Actuator[0] Prepare stream off
02-02 10:55:27.915  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0xab0103, hAc: 0xab0103 type: 20, idx: 0, name = CSLHwTFE
02-02 10:55:27.922  1232  1232 I QTI PowerHAL: Power setBoost: 0, duration: 0
02-02 10:55:27.929  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0xa10105, hAc: 0xa10105 type: 2, idx: 4, name = CSLHwLensActuator
02-02 10:55:27.929  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0x3b0102, hAc: 0x3b0102 type: 1, idx: 13, name = CSLHwImageSensor
02-02 10:55:27.929  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0xcb0104, hAc: 0xcb0104 type: 5, idx: 1, name = CSLHwCSIPHY
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0x7e0107, hAc: 0x7e0107 type: 7, idx: 10, name = CSLHwFlash
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0xc40106, hAc: 0xc40106 type: 19, idx: 12, name = CSLHwOPE
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:943 StreamOff() ZSLPreviewRaw_LT1080p_0 Streaming Off successful:0xb40000758b308c20, last request id 240 is real time 1 cam Id: 0 mode : 1
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.h:2394 SetPipelineStatus() ZSLPreviewRaw_LT1080p_0 status is now PipelineStatus::STREAM_OFF
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][SENSOR ] camxsensornode.cpp:7044 ReleaseResources() Sensor[0] modeBitmask 0x1
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.h:2394 SetPipelineStatus() ZSLPreviewRaw_LT1080p_0 status is now PipelineStatus::RESOURCES_RELEASED
02-02 10:55:27.936  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:1018 Unlink() [ZSLPreviewRaw_LT1080p_0] Unlink for pipeline: 0xb40000758b308c20 Success. Link = 0xb40000758b30c478
02-02 10:55:27.937  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb4000073438ec040) Destroy
02-02 10:55:27.937  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying ZSLPreviewRaw_LT1080p_0
02-02 10:55:27.940  1215  1805 I CamX    : [CONFIG][SENSOR ] camxsensornode.cpp:453 ~SensorNode() Sensor[0] destroy pipeline[0]
02-02 10:55:27.946  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 4194817, cslDeviceIndex 4 oishandle, hDevice 10551557 name:CSLHwLensActuator
02-02 10:55:27.946  1215  1805 I CamX    : [CONFIG][SENSOR ] camxactuator.cpp:142 Destroy() Actuator[0], deviceAcquiredStatus: 0
02-02 10:55:27.947  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 4194817, cslDeviceIndex 1 oishandle, hDevice 13304068 name:CSLHwCSIPHY
02-02 10:55:27.947  1215  1805 I CamX    : [CONFIG][SENSOR ] camxflash.cpp:167 Destroy() Realease Flash[0]
02-02 10:55:27.948  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 4194817, cslDeviceIndex 10 oishandle, hDevice 8257799 name:CSLHwFlash
02-02 10:55:27.951  2120  2444 D BatteryService: uevent={POWER_SUPPLY_DP_DM=0, POWER_SUPPLY_VOLTAGE_QNOVO=-22, POWER_SUPPLY_VOLTAGE_NOW=4411447, POWER_SUPPLY_SW_JEITA_ENABLED=0, POWER_SUPPLY_FORCE_RECHARGE=0, POWER_SUPPLY_CHARGE_CONTROL_LIMIT_MAX=8, POWER_SUPPLY_RECHARGE_SOC=99, POWER_SUPPLY_HEALTH=Good, POWER_SUPPLY_TECHNOLOGY=Li-ion, POWER_SUPPLY_CHARGER_TEMP_MAX=160, POWER_SUPPLY_CHARGE_FULL_DESIGN=5029000, POWER_SUPPLY_FCC_STEPPER_ENABLE=0, SEQNUM=118982, POWER_SUPPLY_INPUT_CURRENT_LIMITED=0, POWER_SUPPLY_CHARGE_CONTROL_LIMIT=0, POWER_SUPPLY_STATUS=Charging, POWER_SUPPLY_CYCLE_COUNT=88, POWER_SUPPLY_BATTERY_CHARGING_ENABLED=1, POWER_SUPPLY_CURRENT_MAX=3000000, POWER_SUPPLY_CHARGE_TERM_CURRENT=-102, POWER_SUPPLY_CAPACITY=96, DEVPATH=/devices/platform/soc/1c40000.qcom,spmi/spmi-0/spmi0-02/1c40000.qcom,spmi:qcom,pmi632@2:qcom,qpnp-smb5/power_supply/battery, POWER_SUPPLY_CHARGE_DONE=0, POWER_SUPPLY_CHARGE_TYPE=Fast, POWER_SUPPLY_CHARGER_TEMP=320, POWER_SUPPLY_CHARGE_RATE=Turbo, POWER_SUPPLY_CURRENT_QNOVO=-22, POWER_SUPPLY_CURRENT_NOW=442962, POWER_SUPPLY_SYSTEM_TEMP_LEVEL=0, POWER_SUPPLY_PRESENT=1, POWER_SUPPLY_PARALLEL_DISABLE=0, POWER_SUPPLY_CHARGE_FULL=4830000, POWER_SUPPLY_TIME_TO_FULL_NOW=3947, POWER_SUPPLY_CONSTANT_CHARGE_CURRENT=3000000, SUBSYSTEM=power_supply, POWER_SUPPLY_SET_SHIP_MODE=0, POWER_SUPPLY_TEMP=283, ACTION=change, POWER_SUPPLY_RERUN_AICL=0, POWER_SUPPLY_AGE=96, POWER_SUPPLY_NAME=battery, POWER_SUPPLY_VOLTAGE_MAX=-22, POWER_SUPPLY_CONSTANT_CHARGE_CURRENT_MAX=3000000, POWER_SUPPLY_CHARGE_COUNTER=4540200, POWER_SUPPLY_STEP_CHARGING_ENABLED=0, POWER_SUPPLY_NUM_SYSTEM_TEMP_LEVELS=8, POWER_SUPPLY_DIE_HEALTH=Cool, POWER_SUPPLY_INPUT_SUSPEND=0}
02-02 10:55:27.967  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 4194817, cslDeviceIndex 13 oishandle, hDevice 3866882 name:CSLHwImageSensor
02-02 10:55:27.985  4687  4894 D CmdCenter: - RowBase2: sPrevModStatus: 1, modStatus: 1
02-02 10:55:27.985  4687  4894 D CmdCenter: - RowBase2: sPrevBatStatus: 2, status: 2
02-02 10:55:27.985  4687  4894 D CmdCenter: - RowBase2: sPrevChargeRate = 3, new = 3
02-02 10:55:27.985  4687  4894 D CmdCenter: - RowBase2: sPrevPlugType: 1 plugType: 1
02-02 10:55:27.988  3179  3179 D DeviceStatisticsService: chargerType=1 batteryLevel=96 totalBatteryCapacity=4729300
02-02 10:55:27.994  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 4194817, cslDeviceIndex 0 oishandle, hDevice 11206915 name:CSLHwTFE
02-02 10:55:28.000  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 4194817, cslDeviceIndex 12 oishandle, hDevice 12845318 name:CSLHwOPE
02-02 10:55:28.002  1215  1805 I CamX    : [CONFIG][FD     ] camxfdmanagernode.cpp:111 ~FDManagerNode() FD frames processed 134 skipped 106 total frames 240
02-02 10:55:28.034  2803  2830 I ndroid.systemu: NativeAlloc concurrent copying GC freed 65731(2249KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 9377KB/18MB, paused 104us total 137.023ms
02-02 10:55:28.167  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb4000073228fa040)
02-02 10:55:28.168  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb4000073228fa040) Destroy
02-02 10:55:28.168  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying SWMFMergeRaw_0
02-02 10:55:28.169  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb400007320350040)
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0x43010f, hAc: 0x43010f type: 19, idx: 12, name = CSLHwOPE
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhwinternal.cpp:2479 CSLHwStreamOffKMDHardwares() Turning off DevH: 0x9b0110, hAc: 0x9b0110 type: 19, idx: 12, name = CSLHwOPE
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:943 StreamOff() ZSLSnapshotYUVHAL_0 Streaming Off successful:0xb40000758b350d40, last request id 235 is real time 0 cam Id: 0 mode : 1
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.h:2394 SetPipelineStatus() ZSLSnapshotYUVHAL_0 status is now PipelineStatus::STREAM_OFF
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.h:2394 SetPipelineStatus() ZSLSnapshotYUVHAL_0 status is now PipelineStatus::RESOURCES_RELEASED
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb400007320350040) Destroy
02-02 10:55:28.170  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying ZSLSnapshotYUVHAL_0
02-02 10:55:28.178  2120  2444 D BatteryService: uevent={POWER_SUPPLY_DP_DM=0, POWER_SUPPLY_VOLTAGE_QNOVO=-22, POWER_SUPPLY_VOLTAGE_NOW=4416313, POWER_SUPPLY_SW_JEITA_ENABLED=0, POWER_SUPPLY_FORCE_RECHARGE=0, POWER_SUPPLY_CHARGE_CONTROL_LIMIT_MAX=8, POWER_SUPPLY_RECHARGE_SOC=99, POWER_SUPPLY_HEALTH=Good, POWER_SUPPLY_TECHNOLOGY=Li-ion, POWER_SUPPLY_CHARGER_TEMP_MAX=160, POWER_SUPPLY_CHARGE_FULL_DESIGN=5029000, POWER_SUPPLY_FCC_STEPPER_ENABLE=0, SEQNUM=118983, POWER_SUPPLY_INPUT_CURRENT_LIMITED=0, POWER_SUPPLY_CHARGE_CONTROL_LIMIT=0, POWER_SUPPLY_STATUS=Charging, POWER_SUPPLY_CYCLE_COUNT=88, POWER_SUPPLY_BATTERY_CHARGING_ENABLED=1, POWER_SUPPLY_CURRENT_MAX=3000000, POWER_SUPPLY_CHARGE_TERM_CURRENT=-102, POWER_SUPPLY_CAPACITY=96, DEVPATH=/devices/platform/soc/1c40000.qcom,spmi/spmi-0/spmi0-02/1c40000.qcom,spmi:qcom,pmi632@2:qcom,qpnp-smb5/power_supply/battery, POWER_SUPPLY_CHARGE_DONE=0, POWER_SUPPLY_CHARGE_TYPE=Taper, POWER_SUPPLY_CHARGER_TEMP=318, POWER_SUPPLY_CHARGE_RATE=Turbo, POWER_SUPPLY_CURRENT_QNOVO=-22, POWER_SUPPLY_CURRENT_NOW=491791, POWER_SUPPLY_SYSTEM_TEMP_LEVEL=0, POWER_SUPPLY_PRESENT=1, POWER_SUPPLY_PARALLEL_DISABLE=0, POWER_SUPPLY_CHARGE_FULL=4830000, POWER_SUPPLY_TIME_TO_FULL_NOW=3946, POWER_SUPPLY_CONSTANT_CHARGE_CURRENT=3000000, SUBSYSTEM=power_supply, POWER_SUPPLY_SET_SHIP_MODE=0, POWER_SUPPLY_TEMP=283, ACTION=change, POWER_SUPPLY_RERUN_AICL=0, POWER_SUPPLY_AGE=96, POWER_SUPPLY_NAME=battery, POWER_SUPPLY_VOLTAGE_MAX=-22, POWER_SUPPLY_CONSTANT_CHARGE_CURRENT_MAX=3000000, POWER_SUPPLY_CHARGE_COUNTER=4540200, POWER_SUPPLY_STEP_CHARGING_ENABLED=0, POWER_SUPPLY_NUM_SYSTEM_TEMP_LEVELS=8, POWER_SUPPLY_DIE_HEALTH=Cool, POWER_SUPPLY_INPUT_SUSPEND=0}
02-02 10:55:28.191  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 2228746, cslDeviceIndex 12 oishandle, hDevice 4391183 name:CSLHwOPE
02-02 10:55:28.196  1215  1805 I CamX    : [CONFIG][CSL    ] camxcslhw.cpp:895 CSLReleaseDeviceHW() hCSL release success: 2228746, cslDeviceIndex 12 oishandle, hDevice 10158352 name:CSLHwOPE
02-02 10:55:28.198  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb40000731c8ef040)
02-02 10:55:28.199  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb40000731c8ef040) Destroy
02-02 10:55:28.199  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying InternalZSLYuv2Jpeg_0
02-02 10:55:28.201  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb40000731a414040)
02-02 10:55:28.201  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb40000731a414040) Destroy
02-02 10:55:28.201  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying MemcpyZSLYUV_0
02-02 10:55:28.203  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb400007316eaa040)
02-02 10:55:28.203  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb400007316eaa040) Destroy
02-02 10:55:28.203  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying SWMFMergeYuv_0
02-02 10:55:28.205  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:783 Flush() Flush took 0 ms. Session (0xb4000073120ed040)
02-02 10:55:28.206  1215  1805 I CamX    : [CONFIG][CORE   ] camxsession.cpp:1104 Destroy() Session (0xb4000073120ed040) Destroy
02-02 10:55:28.206  1215  1805 I CamX    : [CONFIG][CORE   ] camxpipeline.cpp:170 Destroy() Destroying InternalZSLYuv2JpegGPU_0
02-02 10:55:28.210  4687  4894 D CmdCenter: - RowBase2: sPrevModStatus: 1, modStatus: 1
02-02 10:55:28.210  4687  4894 D CmdCenter: - RowBase2: sPrevBatStatus: 2, status: 2
02-02 10:55:28.210  4687  4894 D CmdCenter: - RowBase2: sPrevChargeRate = 3, new = 3
02-02 10:55:28.210  4687  4894 D CmdCenter: - RowBase2: sPrevPlugType: 1 plugType: 1
02-02 10:55:28.212  3179  3179 D DeviceStatisticsService: chargerType=1 batteryLevel=96 totalBatteryCapacity=4729300
02-02 10:55:28.215  1215  1805 W CHIUSECASE: [WARN   ] chitargetbuffermanager.cpp:1749 RemoveTargetBufferPrivate() [FWK_35_TBM] Target buffer seqId=241 is removed with refCount=1
02-02 10:55:28.220  1215  4371 I CHIUSECASE: [CONFIG ] chxextensionmodule.cpp:3815 RequestThreadProcessing() Terminating recovery thread for logical cameraId: 0
02-02 10:55:28.220  1215  1805 I Thermal-Lib: thermal_bandwidth_client_cancel_request: Removing all bw request for camera_bw
02-02 10:55:28.220  1522 30802 I CameraProviderManager: Camera device device@3.5/legacy/0 torch status is now AVAILABLE_OFF
02-02 10:55:28.220  1522 30802 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=1
02-02 10:55:28.221  1522 30802 I CameraProviderManager: Camera device device@3.5/legacy/1 torch status is now AVAILABLE_OFF
02-02 10:55:28.221  1522 30802 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=1, newStatus=1
02-02 10:55:28.221  1522 30802 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 1: No such file or directory (-2)
02-02 10:55:28.221  1522 30802 I CameraProviderManager: Camera device device@3.5/legacy/2 torch status is now AVAILABLE_OFF
02-02 10:55:28.221  1522 30802 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=2, newStatus=1
02-02 10:55:28.221  1522 30802 E CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 2: No such file or directory (-2)
02-02 10:55:28.221  1522 30802 I CameraProviderManager: Camera device device@3.5/legacy/3 torch status is now AVAILABLE_OFF
02-02 10:55:28.221  1522 30802 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=3, newStatus=1
02-02 10:55:28.221  1522 30802 I CameraProviderManager: Camera device device@3.5/legacy/4 torch status is now AVAILABLE_OFF
02-02 10:55:28.221  1522 30802 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=4, newStatus=1
02-02 10:55:28.221  1215  1805 I CamX    : [CONFIG][HAL    ] camxhaldevice.cpp:1481 CloseCachedSensorHandles() Releasing resources for Logical CameraID=0, PhysicalID=0
02-02 10:55:28.221  1215  1805 I CamX    : [CONFIG][HAL    ] camxhal3.cpp:945 close() HalOp: End CLOSE, logicalCameraId: 0, cameraId: 0
02-02 10:55:28.221  1215  1805 I CamX    : [CONFIG][HAL    ] camxthermalmanager.cpp:182 UnregisterHALDevice() Unregistered pHALDevice=0xb400007353ae7040 CameraId=0
02-02 10:55:28.222  1215  1805 I CamX    : [CONFIG][HAL    ] camxhaldevice.cpp:1336 UnLoadStaticlibs() Freeing lib=libllvm-qcom.so
02-02 10:55:28.222  1215  1805 I CamX    : [CONFIG][HAL    ] camxhaldevice.cpp:1336 UnLoadStaticlibs() Freeing lib=libCB.so
02-02 10:55:28.222  1215  1805 I CamX    : [CONFIG][HAL    ] camxhaldevice.cpp:1336 UnLoadStaticlibs() Freeing lib=libOpenCL.so
02-02 10:55:28.222  1215  1805 I CamX    : [CONFIG][HAL    ] camxhaldevice.cpp:145 Destroy() MEM monitor pid=1215 HWM=128740 RSS=50540
02-02 10:55:28.223  1582  1729 I ThermalEngine: Thermal-Server: removing client on fd 55
02-02 10:55:28.228  1522 30802 I CameraLatencyHistogram: Stream 1 dequeueBuffer latency histogram (242) samples:
02-02 10:55:28.228  1522 30802 I CameraLatencyHistogram:         5     10     15     20     25     30     35     40     45    inf (max ms)
02-02 10:55:28.228  1522 30802 I CameraLatencyHistogram:      99.17   0.83   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00 (%)
02-02 10:55:28.229  1582  1730 I ThermalEngine: Mitigation:modem_bw[MODEM]:0
02-02 10:55:28.229  1582  1730 I ThermalEngine: Monitor:INACTIVE:CAMERA-BW-SCORE-MONITOR:modem_bw=1:camera_bw_score=0
02-02 10:55:28.230  1522 30802 I CameraLatencyHistogram: Stream 2 dequeueBuffer latency histogram (1) samples:
02-02 10:55:28.230  1522 30802 I CameraLatencyHistogram:         5     10     15     20     25     30     35     40     45    inf (max ms)
02-02 10:55:28.230  1522 30802 I CameraLatencyHistogram:      0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   100.00 (%)
02-02 10:55:28.232  1522 30802 I CameraLatencyHistogram: Stream 3 dequeueBuffer latency histogram (242) samples:
02-02 10:55:28.232  1522 30802 I CameraLatencyHistogram:         5     10     15     20     25     30     35     40     45    inf (max ms)
02-02 10:55:28.232  1522 30802 I CameraLatencyHistogram:      92.98   0.83   1.24   1.65   1.65   0.41   0.83   0.00   0.00   0.41 (%)
02-02 10:55:28.232  1522 30802 I Camera3-Device: disconnectImpl: X
02-02 10:55:28.234  1522 30802 I CameraService: disconnect: Disconnected client for camera 0 for PID 32546
02-02 10:55:28.235  4644 32660 E CameraManagerGlobal: Camera 4 is not available. Ignore physical camera status change
02-02 10:55:28.235 32546  1532 E CameraManagerGlobal: Camera 4 is not available. Ignore physical camera status change
02-02 10:55:28.236 32546  4306 E McfMlStateMachine: mcf not supported by current mode
02-02 10:55:28.250  4375  4415 D PostProcServiceImpl: unregisterClient(0)
02-02 10:55:28.256  4375  4415 E PostProcThread: haltThreadSync
02-02 10:55:28.256  4375  4415 W PostProc: cancelCurrentJob: No jobs are being worked upon
02-02 10:55:28.262  4375  4415 E PostProcThread: ~PostProcThread
02-02 10:55:28.262  4375  4415 W PostProc: cancelCurrentJob: No jobs are being worked upon
02-02 10:55:28.286  4375  4375 E PostProcServiceImpl: deinitialize: service already deinitialized
02-02 10:55:28.288 32708 32708 D camera2.background: killing process com.motorola.camera2:postProcService, pid = 4375
02-02 10:55:28.288 32708 32708 I Process : Sending signal. PID: 4375 SIG: 9
02-02 10:55:28.316  2120  5266 I ActivityManager: Process com.motorola.camera2:postProcService (pid 4375) has died: fg  SVC
02-02 10:55:28.316  1062  1062 I Zygote  : Process 4375 exited due to signal 9 (Killed)
02-02 10:55:28.317  2120  2319 I libprocessgroup: Successfully killed process cgroup uid 10165 pid 4375 in 0ms
02-02 10:55:28.442  1210 14669 E sensors-hal: handle_sns_client_event:62, mot_disprot_event: now=92369849200578 ts=92369648602857, type=0, status=3
02-02 10:55:28.442  1210 14669 E sensors-hal: handle_sns_client_event:62, mot_disprot_event: now=92369849362453 ts=92369774087232, type=16, status=3
02-02 10:55:28.662  2120  2120 E AudioService.OrientationHelper: Unknown device rotation
02-02 10:55:28.798  1210  2446 D slpi    : vcnl36866_ALS_handle:lux:535.208008, last_ps:far[494], als_raw:1759, ir_raw:280, als_scale:1.346320, THDH:1336,THDL:988,CONF:5102, PSTH  L 396 H 703
02-02 10:55:28.798  1210  2446 I slpi    : vcnl36866_handle_interrupt: 0, 0, 1, 496
02-02 10:55:29.102  1210 14669 E sensors-hal: handle_sns_client_event:62, mot_disprot_event: now=92370508837884 ts=92370401510826, type=1, status=3
02-02 10:55:29.103  1232  1232 I QTI PowerHAL: Power setBoost: 0, duration: 0
02-02 10:55:29.205  1210  2446 D slpi    : vcnl36866_ALS_handle:lux:624.967102, last_ps:far[496], als_raw:2054, ir_raw:251, als_scale:1.346320, THDH:2022,THDL:1496,CONF:5102, PSTH  L 396 H 703
02-02 10:55:29.205  1210  2446 I slpi    : vcnl36866_handle_interrupt: 0, 0, 1, 496
02-02 10:55:29.321  1210 14669 E sensors-hal: handle_sns_client_event:62, mot_disprot_event: now=92370728022958 ts=92370610651919, type=16, status=3
02-02 10:55:29.322  1209  1948 D audio_hw_primary: adev_set_parameters: enter: rotation=270
02-02 10:55:29.323  1209  1948 V msm8974_platform: platform_set_parameters: enter: rotation=270
02-02 10:55:29.323  1209  1948 V msm8974_platform: platform_set_parameters: exit with code(0)
02-02 10:55:29.323  1209  1948 D audio_hw_primary: adev_set_parameters: exit with code(0) takes 0.12 ms
02-02 10:55:29.473  2120  2444 D BatteryService: uevent={POWER_SUPPLY_DP_DM=0, POWER_SUPPLY_VOLTAGE_QNOVO=-22, POWER_SUPPLY_VOLTAGE_NOW=4415729, POWER_SUPPLY_SW_JEITA_ENABLED=0, POWER_SUPPLY_FORCE_RECHARGE=0, POWER_SUPPLY_CHARGE_CONTROL_LIMIT_MAX=8, POWER_SUPPLY_RECHARGE_SOC=99, POWER_SUPPLY_HEALTH=Good, POWER_SUPPLY_TECHNOLOGY=Li-ion, POWER_SUPPLY_CHARGER_TEMP_MAX=160, POWER_SUPPLY_CHARGE_FULL_DESIGN=5029000, POWER_SUPPLY_FCC_STEPPER_ENABLE=0, SEQNUM=118984, POWER_SUPPLY_INPUT_CURRENT_LIMITED=0, POWER_SUPPLY_CHARGE_CONTROL_LIMIT=0, POWER_SUPPLY_STATUS=Charging, POWER_SUPPLY_CYCLE_COUNT=88, POWER_SUPPLY_BATTERY_CHARGING_ENABLED=1, POWER_SUPPLY_CURRENT_MAX=3000000, POWER_SUPPLY_CHARGE_TERM_CURRENT=-102, POWER_SUPPLY_CAPACITY=96, DEVPATH=/devices/platform/soc/1c40000.qcom,spmi/spmi-0/spmi0-02/1c40000.qcom,spmi:qcom,pmi632@2:qcom,qpnp-smb5/power_supply/battery, POWER_SUPPLY_CHARGE_DONE=0, POWER_SUPPLY_CHARGE_TYPE=Taper, POWER_SUPPLY_CHARGER_TEMP=316, POWER_SUPPLY_CHARGE_RATE=Turbo, POWER_SUPPLY_CURRENT_QNOVO=-22, POWER_SUPPLY_CURRENT_NOW=475769, POWER_SUPPLY_SYSTEM_TEMP_LEVEL=0, POWER_SUPPLY_PRESENT=1, POWER_SUPPLY_PARALLEL_DISABLE=0, POWER_SUPPLY_CHARGE_FULL=4830000, POWER_SUPPLY_TIME_TO_FULL_NOW=3944, POWER_SUPPLY_CONSTANT_CHARGE_CURRENT=3000000, SUBSYSTEM=power_supply, POWER_SUPPLY_SET_SHIP_MODE=0, POWER_SUPPLY_TEMP=284, ACTION=change, POWER_SUPPLY_RERUN_AICL=0, POWER_SUPPLY_AGE=96, POWER_SUPPLY_NAME=battery, POWER_SUPPLY_VOLTAGE_MAX=-22, POWER_SUPPLY_CONSTANT_CHARGE_CURRENT_MAX=3000000, POWER_SUPPLY_CHARGE_COUNTER=4540200, POWER_SUPPLY_STEP_CHARGING_ENABLED=0, POWER_SUPPLY_NUM_SYSTEM_TEMP_LEVELS=8, POWER_SUPPLY_DIE_HEALTH=Cool, POWER_SUPPLY_INPUT_SUSPEND=0}
02-02 10:55:29.512  4687  4894 D CmdCenter: - RowBase2: sPrevModStatus: 1, modStatus: 1
02-02 10:55:29.513  4687  4894 D CmdCenter: - RowBase2: sPrevBatStatus: 2, status: 2
02-02 10:55:29.513  4687  4894 D CmdCenter: - RowBase2: sPrevChargeRate = 3, new = 3
02-02 10:55:29.513  4687  4894 D CmdCenter: - RowBase2: sPrevPlugType: 1 plugType: 1
02-02 10:55:29.516  3179  3179 D DeviceStatisticsService: chargerType=1 batteryLevel=96 totalBatteryCapacity=4729300
02-02 10:55:29.760  2120  2120 E AudioService.OrientationHelper: Unknown device rotation
02-02 10:55:29.963  1886  1886 W adbd    : timeout expired while flushing socket, closing
02-02 10:55:30.018  1210  2446 D slpi    : vcnl36866_ALS_handle:lux:446.057343, last_ps:far[492], als_raw:1466, ir_raw:282, als_scale:1.346320, THDH:2362,THDL:1746,CONF:5102, PSTH  L 396 H 703
02-02 10:55:30.018  1210  2446 I slpi    : vcnl36866_handle_interrupt: 0, 0, 1, 496
02-02 10:55:31.068  3906  3929 I com.reevcable: NativeAlloc concurrent copying GC freed 19827(852KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 21MB/43MB, paused 128us total 196.252ms
02-02 10:55:31.500  3906  3906 D OpenCV/StaticHelper: Trying to get library list
02-02 10:55:31.845  3906  3906 E OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
02-02 10:55:31.845  3906  3906 D OpenCV/StaticHelper: Library list: ""
02-02 10:55:31.845  3906  3906 D OpenCV/StaticHelper: First attempt to load libs
02-02 10:55:31.845  3906  3906 D OpenCV/StaticHelper: Trying to init OpenCV libs
02-02 10:55:31.845  3906  3906 D OpenCV/StaticHelper: Trying to load library opencv_java4
02-02 10:55:31.846  3906  3906 D OpenCV/StaticHelper: Library opencv_java4 loaded
02-02 10:55:31.846  3906  3906 D OpenCV/StaticHelper: First attempt to load libs is OK
02-02 10:55:31.848  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.848  3906  3906 I OpenCV/StaticHelper: General configuration for OpenCV 4.1.0 =====================================
02-02 10:55:31.848  3906  3906 I OpenCV/StaticHelper:   Version control:               4.1.0
02-02 10:55:31.848  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:   Platform:
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     Timestamp:                   2019-04-07T19:03:43Z
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     Host:                        Linux 4.15.0-47-generic x86_64
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     Target:                      Android 1 aarch64
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     CMake:                       3.6.0-rc2
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     CMake generator:             Ninja
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     CMake build tool:            /opt/android/android-sdk.gradle/cmake/3.6.4111459/bin/ninja
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     Configuration:               Release
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:   CPU/HW features:
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     Baseline:                    NEON FP16
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:   C/C++:
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     Built as dynamic libs?:      NO
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     C++ Compiler:                /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  (ver 7.0)
02-02 10:55:31.849  3906  3906 I OpenCV/StaticHelper:     C++ flags (Release):         -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O2 -DNDEBUG   -DNDEBUG
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     C++ flags (Debug):           -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG -g
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     C Compiler:                  /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     C flags (Release):           -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O2 -DNDEBUG   -DNDEBUG
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     C flags (Debug):             -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG -g
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     Linker flags (Release):      -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /opt/android/android-ndk-r18b/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/opt/android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     Linker flags (Debug):        -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /opt/android/android-ndk-r18b/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/opt/android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     ccache:                      YES
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     Precompiled headers:         NO
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     Extra dependencies:          z dl m log
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     3rdparty dependencies:       tbb libcpufeatures libprotobuf libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc tegra_hal
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:   OpenCV modules:
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java ml objdetect photo stitching video videoio
02-02 10:55:31.850  3906  3906 I OpenCV/StaticHelper:     Disabled:                    world
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Disabled by dependency:      -
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Unavailable:                 gapi js python2 python3 ts
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Applications:                -
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Documentation:               NO
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Non-free algorithms:         NO
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:   Android NDK:                   /opt/android/android-ndk-r18b (ver 18.1.5063045)
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Android ABI:                 arm64-v8a
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     NDK toolchain:               aarch64-linux-android-clang
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     STL type:                    c++_static
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     Native API level:            21
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:   Android SDK:                   /opt/android/android-sdk.gradle (tools: 26.1.1 build tools: 28.0.3)
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:   GUI:
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:   Media I/O:
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     ZLib:                        z (ver 1.2.7)
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     WEBP:                        build (ver encoder: 0x020e)
02-02 10:55:31.851  3906  3906 I OpenCV/StaticHelper:     PNG:                         build (ver 1.6.36)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     TIFF:                        build (ver 42 - 4.0.10)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     JPEG 2000:                   build (ver 1.900.1)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     OpenEXR:                     build (ver 1.7.1)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     HDR:                         YES
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     SUNRASTER:                   YES
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     PXM:                         YES
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     PFM:                         YES
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:   Video I/O:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:   Parallel framework:            TBB (ver 2018.0 interface 10001)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:   Trace:                         YES (built-in)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:   Other third-party libraries:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     Custom HAL:                  YES (carotene (ver 0.0.1))
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     Protobuf:                    build (3.5.1)
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:   Python (for build):            /usr/bin/python2.7
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:   Java:                          export all functions
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     ant:                         NO
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     Java wrappers:               YES
02-02 10:55:31.852  3906  3906 I OpenCV/StaticHelper:     Java tests:                  NO
02-02 10:55:31.853  3906  3906 I OpenCV/StaticHelper:
02-02 10:55:31.853  3906  3906 I OpenCV/StaticHelper:   Install to:                    /build/master_pack-android/build/o4a/install
02-02 10:55:31.853  3906  3906 I OpenCV/StaticHelper: -----------------------------------------------------------------
02-02 10:55:31.865  3906  3906 I Choreographer: Skipped 236 frames!  The application may be doing too much work on its main thread.
02-02 10:55:31.883  2120  4588 V WindowManager: Changing focus from null to Window{ea2b1d5 u0 com.reevcable/com.websitebeaver.documentscanner.DocumentScannerActivity} displayId=0
02-02 10:55:31.903  3906  3906 D AndroidRuntime: Shutting down VM
02-02 10:55:31.907  3906  3906 E AndroidRuntime: FATAL EXCEPTION: main
02-02 10:55:31.907  3906  3906 E AndroidRuntime: Process: com.reevcable, PID: 3906
02-02 10:55:31.907  3906  3906 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:283)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1436)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at com.websitebeaver.documentscanner.ui.ImageCropView.onDraw(ImageCropView.kt:225)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22406)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21282)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22137)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22409)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21282)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22137)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21273)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22137)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21273)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22137)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21273)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22137)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21273)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22137)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.draw(View.java:22409)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:858)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21282)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4252)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3979)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3250)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2062)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8424)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:250)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7851)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-02 10:55:31.907  3906  3906 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
02-02 10:55:31.914  2120  4509 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-02 10:55:31.915  2120  4588 W ActivityTaskManager:   Force finishing activity com.reevcable/com.websitebeaver.documentscanner.DocumentScannerActivity
02-02 10:55:31.922  2120 16817 E FrameEvents: updateAcquireFence: Did not find frame.
02-02 10:55:31.932  2120  2284 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-02 10:55:31.933  2120  2284 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-02 10:55:31.984  2120  2264 V WindowManager: Changing focus from Window{ea2b1d5 u0 com.reevcable/com.websitebeaver.documentscanner.DocumentScannerActivity} to Window{1e80bd0 u0 Application Error: com.reevcable} displayId=0
02-02 10:55:32.048  2120  2267 I WindowManager: SURFACE show Surface(name=Application Error: com.reevcable)/@0x13e0900 on display:0
```

You can see there is a canvas exception which leads me to believe there is a RAM issue when the image is loaded into a canvas. I tried tweaking the params but it does not work:

```ts
const r: ScanDocumentResponse = await DocumentScanner.scanDocument({
        croppedImageQuality: 80,
        maxNumDocuments: 1,
        responseType: ResponseType.ImageFilePath,
      });
```

I'm running rn 0.70.6 with Expo 47. Any ideas for a workaround?

**Comment by ospfranco** [comment]
Looking into the source code here are some theories on what could be fixed:

- According to this [stack_overflow question](https://stackoverflow.com/questions/18228365/how-to-capture-low-resolution-picture-using-android-camera) using [EXTRA_OUTPUT](https://github.com/WebsiteBeaver/android-document-scanner/blob/master/documentscanner/src/main/java/com/websitebeaver/documentscanner/utils/CameraUtil.kt#L71) increases the file size.

- You seem to be taking the raw image data and [raw drawing it into a buffer/canvas](https://github.com/WebsiteBeaver/android-document-scanner/blob/master/documentscanner/src/main/java/com/websitebeaver/documentscanner/extensions/Canvas.kt) to show the preview, which of course on RAM-constrained devices will cause a crash... you probably want to generate a smaller preview?

**Comment by dmarcs** [comment]
@ospfranco thanks for looking into this. I'm using `EXTRA_OUTPUT` intentionally because I want the final image to be as large as possible.

It sounds like I can fix this problem by scaling the image before showing the preview.

**Comment by dmarcs** [comment]
I can't reproduce this error, so I need someone to confirm that it's fixed in [0.73](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/tree/0.7.3)

https://github.com/WebsiteBeaver/android-document-scanner/pull/26

if photo is larger than 100MB, resize the photo so it's smaller

**Comment by ospfranco** [comment]
Wouldn't close the issue until it is confirmed to be fixed

**Comment by ZXY101** [comment]
@ospfranco I was experiencing this issue when I used my front camera, can confirm it's fixed for me in 0.7.3

**Comment by ospfranco** [comment]
I would still argue loading a 100mb photo is not ideal... considering a normal jpeg is 4 mbs. I can definitely see lower end android devices still crashing.
